### ISSUE TITLE
README's first example does not run as desired.

### ISSUE THREAD

**Issue by soulne4ny** [nats-io/node-nats-streaming#20]
The code I run is taken from README.md _Basic usage_ with first line modified. It is
```javascript
var stan = require( 'node-nats-streaming' ).connect( 'test-cluster', 'client-123', 'nats://localhost:4222' );

stan.on( 'connect', function() {
    // Simple Publisher (all publishes are async in the node version of the client)
    stan.publishAsync( 'foo', 'Hello World!', function( err, guid ) {
        if ( err ) {
            console.log( 'publish failed: ' + err );
        } else {
            console.log( 'published message with guid: ' + guid );
        }
    } );

    // Subscriber can specify how many existing messages to get.
    var subscription = stan.subscribe( 'foo' );
    subscription.on( 'message', function( msg ) {
        console.log( 'Received a message: ' + msg.getData() );
    } );

    // Unsubscribe
    subscription.unsubscribe();

    // Close connection
    stan.close();
} );
```

The result it produces
```
$ node a.js
Error
    at Client.publish (/.../node_modules/nats/lib/nats.js:930:15)
    at Client.request (/.../node_modules/nats/lib/nats.js:1123:10)
    at Client.<anonymous> (/.../node_modules/node-nats-streaming/lib/stan.js:254:13)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.connectCB (/.../node_modules/nats/lib/nats.js:330:10)
    at /.../node_modules/nats/lib/nats.js:755:67
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:725:33)
    at Socket.<anonymous> (/.../node_modules/nats/lib/nats.js:405:16)
    at emitOne (events.js:96:13)
Error
    at Client.publish (/.../node_modules/nats/lib/nats.js:930:15)
    at Stan.publishAsync (/.../node_modules/node-nats-streaming/lib/stan.js:410:11)
    at Stan.<anonymous> (/.../a.js:6:10)
    at emitOne (events.js:96:13)
    at Stan.emit (events.js:188:7)
    at /.../node_modules/node-nats-streaming/lib/stan.js:260:12
    at Object.callback (/.../node_modules/nats/lib/nats.js:1121:9)
    at Client.processMsg (/.../node_modules/nats/lib/nats.js:873:17)
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:805:24)
    at Socket.<anonymous> (/.../node_modules/nats/lib/nats.js:405:16)
Error
    at Client.publish (/.../node_modules/nats/lib/nats.js:930:15)
    at Client.request (/.../node_modules/nats/lib/nats.js:1123:10)
    at Stan.subscribe (/.../node_modules/node-nats-streaming/lib/stan.js:493:11)
    at Stan.<anonymous> (/.../a.js:15:29)
    at emitOne (events.js:96:13)
    at Stan.emit (events.js:188:7)
    at /.../node_modules/node-nats-streaming/lib/stan.js:260:12
    at Object.callback (/.../node_modules/nats/lib/nats.js:1121:9)
    at Client.processMsg (/.../node_modules/nats/lib/nats.js:873:17)
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:805:24)
Error
    at Client.publish (/.../node_modules/nats/lib/nats.js:930:15)
    at Client.request (/.../node_modules/nats/lib/nats.js:1123:10)
    at Subscription.unsubscribe (/.../node_modules/node-nats-streaming/lib/stan.js:587:19)
    at Stan.<anonymous> (/.../a.js:21:18)
    at emitOne (events.js:96:13)
    at Stan.emit (events.js:188:7)
    at /.../node_modules/node-nats-streaming/lib/stan.js:260:12
    at Object.callback (/.../node_modules/nats/lib/nats.js:1121:9)
    at Client.processMsg (/.../node_modules/nats/lib/nats.js:873:17)
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:805:24)
Error
    at Client.publish (/.../node_modules/nats/lib/nats.js:930:15)
    at Client.request (/.../node_modules/nats/lib/nats.js:1123:10)
    at Stan.close (/.../node_modules/node-nats-streaming/lib/stan.js:299:11)
    at Stan.<anonymous> (/.../a.js:24:10)
    at emitOne (events.js:96:13)
    at Stan.emit (events.js:188:7)
    at /.../node_modules/node-nats-streaming/lib/stan.js:260:12
    at Object.callback (/.../node_modules/nats/lib/nats.js:1121:9)
    at Client.processMsg (/.../node_modules/nats/lib/nats.js:873:17)
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:805:24)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stan: invalid subscription
    at /.../node_modules/node-nats-streaming/lib/stan.js:592:26
    at Object.callback (/.../node_modules/nats/lib/nats.js:1121:9)
    at Client.processMsg (/.../node_modules/nats/lib/nats.js:873:17)
    at Client.processInbound (/.../node_modules/nats/lib/nats.js:805:24)
    at Socket.<anonymous> (/.../node_modules/nats/lib/nats.js:405:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by aricart** [comment]
Thanks for finding this. The issue is a subtle one. The unsubscribe/close are getting executed before the subscription is fully processed. I will add a comment to the example. To make the sample work correctly requires a bit more effort:

```javascript
#!/usr/bin/env node

"use-strict";

var stan = require('node-nats-streaming').connect('test-cluster', 'test');

stan.on('connect', function () {
  
  // Simple Publisher (all publishes are async in the node version of the client)
  var payload = 'Hello World!' + Date.now();
  stan.publishAsync('foo', payload, function(err, guid){
    if(err) {
      console.log('publish failed: ' + err);
    } else {
      console.log('published message with guid: ' + guid + " payload:" + payload);
    }
  });

  // Subscriber can specify how many existing messages to get.
  var opts = stan.subscriptionOptions().setStartWithLastReceived();
  var subscription = stan.subscribe('foo', opts);
  subscription.on('message', function (msg) {
    console.log('Received a message: ' + msg.getData());
  });

  setTimeout(function() {
    subscription.unsubscribe();
    subscription.on('unsubscribed', function() {
      stan.close();
    });
  }, 1000);
});

stan.on('close', function() {
  process.exit();
});
```

**Comment by soulne4ny** [comment]
@aricart, thank you for correcting the example. Now it says
`Received a message: Hello World!1476277427730` and `published message with guid: IB6GO035H15FLHWJP5WIYN payload:Hello World!1476277427730`.

However, as well it still produces 7 errors as above. I suspect it the nats configuration could be the cause. I've tried an example from _node-nats_ repo. It is producing the same errors in my case.  However, I have no clue what could it be.

**Comment by aricart** [comment]
I ran the program several times. Didn't run into the error you have.

```[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280624154
Received a message: Hello World!1476280702944
published message with guid: 403BYUBL3I5QVZN2QOL4AZ payload:Hello World!1476280702944
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280702944
Received a message: Hello World!1476280704976
published message with guid: Y6VGVKBLZH22177LZIMOKU payload:Hello World!1476280704976
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280704976
Received a message: Hello World!1476280706922
published message with guid: OORU10TQDQFQKYRNUTT348 payload:Hello World!1476280706922
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280706922
Received a message: Hello World!1476280708874
published message with guid: LNZZ8TIOXXX568942QUSL3 payload:Hello World!1476280708874
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280708874
Received a message: Hello World!1476280710838
published message with guid: NOJ47V0CO84HYKCTVDFCTJ payload:Hello World!1476280710838
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
published message with guid: 7FOTLCFDF1625NVZJN7KP0 payload:Hello World!1476280712692
Received a message: Hello World!1476280712692
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280712692
Received a message: Hello World!1476280714671
published message with guid: BLEOQ7CRG6Q435S87JZZDH payload:Hello World!1476280714671
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280714671
Received a message: Hello World!1476280716606
published message with guid: O4R1RY9IJVY5I0G6TL1GPO payload:Hello World!1476280716606
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280716606
Received a message: Hello World!1476280720034
published message with guid: SLPF1N6LG4Q8M6LK20LGWM payload:Hello World!1476280720034
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280720034
Received a message: Hello World!1476280722253
published message with guid: 0ST6OPH046G1V81TGCNYEB payload:Hello World!1476280722253
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280722253
Received a message: Hello World!1476280724122
published message with guid: EOJO0SQNY90A234GLGHXEC payload:Hello World!1476280724122
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280724122
Received a message: Hello World!1476280726080
published message with guid: MH6G11U0F2EIVJ5LD21C9G payload:Hello World!1476280726080
[albertoricart@barsoom:~/node-example-test]$ node basic.js 
Received a message: Hello World!1476280726080
Received a message: Hello World!1476280728050
published message with guid: JNWTMK4HNE5D72A3V2W386 payload:Hello World!1476280728050
[albertoricart@barsoom:~/node-example-test]$ 
```

**Comment by aricart** [comment]
Can you attach your node_modules/nats/lib/nats.js file. Your version is not matching mine.

Alternatively, you can delete nats and node-nats-streaming from node_modules, and do `npm install node-nats-streaming`

**Comment by soulne4ny** [comment]
Thank you, @aricart. I've put _basic.js_ into a new catalog and installed _node-nats-streaming_ as you've shown. It works.
